apiVersion: etcd.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  name: test-cluster-bitnami
  namespace: default
spec:
  size: 3
  version: "3.5.9"
  repository: "bitnami/etcd"
  storage:
    size: "1Gi"
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"
