apiVersion: etcd.etcd.io/v1alpha1
kind: EtcdCluster
metadata:
  name: test-resource-limits
  namespace: default
spec:
  size: 1
  repository: quay.io/coreos/etcd
  version: v3.5.21
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
