apiVersion: etcd.etcd.io/v1alpha1
kind: EtcdRestore
metadata:
  labels:
    app.kubernetes.io/name: etcd-k8s-operator
    app.kubernetes.io/managed-by: kustomize
  name: etcdrestore-sample
spec:
  # TODO(user): Add fields here
